# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from swagger_server.models.base_model_ import Model
from swagger_server import util


class CategoryResponse(Model):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """

    def __init__(self, category_id: int = None):  # noqa: E501
        """CategoryResponse - a model defined in Swagger

        :param category_id: The category_id of this CategoryResponse.  # noqa: E501
        :type category_id: int
        """
        self.swagger_types = {'category_id': int}

        self.attribute_map = {'category_id': 'category_id'}
        self._category_id = category_id

    @classmethod
    def from_dict(cls, dikt) -> 'CategoryResponse':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The CategoryResponse of this CategoryResponse.  # noqa: E501
        :rtype: CategoryResponse
        """
        return util.deserialize_model(dikt, cls)

    @property
    def category_id(self) -> int:
        """Gets the category_id of this CategoryResponse.


        :return: The category_id of this CategoryResponse.
        :rtype: int
        """
        return self._category_id

    @category_id.setter
    def category_id(self, category_id: int):
        """Sets the category_id of this CategoryResponse.


        :param category_id: The category_id of this CategoryResponse.
        :type category_id: int
        """

        self._category_id = category_id
