# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from swagger_server.models.base_model_ import Model
from swagger_server import util


class CustomerResponse(Model):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """

    def __init__(self, customer_id: int = None):  # noqa: E501
        """CustomerResponse - a model defined in Swagger

        :param customer_id: The customer_id of this CustomerResponse.  # noqa: E501
        :type customer_id: int
        """
        self.swagger_types = {"customer_id": int}

        self.attribute_map = {"customer_id": "customer_id"}
        self._customer_id = customer_id

    @classmethod
    def from_dict(cls, dikt) -> "CustomerResponse":
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The CustomerResponse of this CustomerResponse.  # noqa: E501
        :rtype: CustomerResponse
        """
        return util.deserialize_model(dikt, cls)

    @property
    def customer_id(self) -> int:
        """Gets the customer_id of this CustomerResponse.


        :return: The customer_id of this CustomerResponse.
        :rtype: int
        """
        return self._customer_id

    @customer_id.setter
    def customer_id(self, customer_id: int):
        """Sets the customer_id of this CustomerResponse.


        :param customer_id: The customer_id of this CustomerResponse.
        :type customer_id: int
        """

        self._customer_id = customer_id
