# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from swagger_server.models.base_model_ import Model
from swagger_server import util


class ExpenseResponse(Model):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """

    def __init__(self, expense_id: int = None):  # noqa: E501
        """ExpenseResponse - a model defined in Swagger

        :param expense_id: The expense_id of this ExpenseResponse.  # noqa: E501
        :type expense_id: int
        """
        self.swagger_types = {'expense_id': int}

        self.attribute_map = {'expense_id': 'expense_id'}
        self._expense_id = expense_id

    @classmethod
    def from_dict(cls, dikt) -> 'ExpenseResponse':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The ExpenseResponse of this ExpenseResponse.  # noqa: E501
        :rtype: ExpenseResponse
        """
        return util.deserialize_model(dikt, cls)

    @property
    def expense_id(self) -> int:
        """Gets the expense_id of this ExpenseResponse.


        :return: The expense_id of this ExpenseResponse.
        :rtype: int
        """
        return self._expense_id

    @expense_id.setter
    def expense_id(self, expense_id: int):
        """Sets the expense_id of this ExpenseResponse.


        :param expense_id: The expense_id of this ExpenseResponse.
        :type expense_id: int
        """

        self._expense_id = expense_id
