# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from swagger_server.models.base_model_ import Model
from swagger_server import util


class Expense(Model):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """

    def __init__(
        self,
        amount: float = None,
        description: str = None,
        accrual_date: str = None,
        transaction_date: str = None,
        customer_id: int = None,
    ):  # noqa: E501
        """Expense - a model defined in Swagger

        :param amount: The amount of this Expense.  # noqa: E501
        :type amount: float
        :param description: The description of this Expense.  # noqa: E501
        :type description: str
        :param accrual_date: The accrual_date of this Expense.  # noqa: E501
        :type accrual_date: str
        :param transaction_date: The transaction_date of this Expense.  # noqa: E501
        :type transaction_date: str
        :param customer_id: The customer_id of this Expense.  # noqa: E501
        :type customer_id: int
        """
        self.swagger_types = {
            'amount': float,
            'description': str,
            'accrual_date': str,
            'transaction_date': str,
            'customer_id': int,
        }

        self.attribute_map = {
            'amount': 'amount',
            'description': 'description',
            'accrual_date': 'accrual_date',
            'transaction_date': 'transaction_date',
            'customer_id': 'customer_id',
        }
        self._amount = amount
        self._description = description
        self._accrual_date = accrual_date
        self._transaction_date = transaction_date
        self._customer_id = customer_id

    @classmethod
    def from_dict(cls, dikt) -> 'Expense':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The Expense of this Expense.  # noqa: E501
        :rtype: Expense
        """
        return util.deserialize_model(dikt, cls)

    @property
    def amount(self) -> float:
        """Gets the amount of this Expense.


        :return: The amount of this Expense.
        :rtype: float
        """
        return self._amount

    @amount.setter
    def amount(self, amount: float):
        """Sets the amount of this Expense.


        :param amount: The amount of this Expense.
        :type amount: float
        """

        self._amount = amount

    @property
    def description(self) -> str:
        """Gets the description of this Expense.


        :return: The description of this Expense.
        :rtype: str
        """
        return self._description

    @description.setter
    def description(self, description: str):
        """Sets the description of this Expense.


        :param description: The description of this Expense.
        :type description: str
        """

        self._description = description

    @property
    def accrual_date(self) -> str:
        """Gets the accrual_date of this Expense.


        :return: The accrual_date of this Expense.
        :rtype: str
        """
        return self._accrual_date

    @accrual_date.setter
    def accrual_date(self, accrual_date: str):
        """Sets the accrual_date of this Expense.


        :param accrual_date: The accrual_date of this Expense.
        :type accrual_date: str
        """

        self._accrual_date = accrual_date

    @property
    def transaction_date(self) -> str:
        """Gets the transaction_date of this Expense.


        :return: The transaction_date of this Expense.
        :rtype: str
        """
        return self._transaction_date

    @transaction_date.setter
    def transaction_date(self, transaction_date: str):
        """Sets the transaction_date of this Expense.


        :param transaction_date: The transaction_date of this Expense.
        :type transaction_date: str
        """

        self._transaction_date = transaction_date

    @property
    def customer_id(self) -> int:
        """Gets the customer_id of this Expense.


        :return: The customer_id of this Expense.
        :rtype: int
        """
        return self._customer_id

    @customer_id.setter
    def customer_id(self, customer_id: int):
        """Sets the customer_id of this Expense.


        :param customer_id: The customer_id of this Expense.
        :type customer_id: int
        """

        self._customer_id = customer_id
