# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from swagger_server.models.base_model_ import Model
from swagger_server import util


class FiscalYear(Model):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """

    def __init__(self, fiscal_year: int = None):  # noqa: E501
        """FiscalYear - a model defined in Swagger

        :param fiscal_year: The fiscal_year of this FiscalYear.  # noqa: E501
        :type fiscal_year: int
        """
        self.swagger_types = {"fiscal_year": int}

        self.attribute_map = {"fiscal_year": "fiscal_year"}
        self._fiscal_year = fiscal_year

    @classmethod
    def from_dict(cls, dikt) -> "FiscalYear":
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The FiscalYear of this FiscalYear.  # noqa: E501
        :rtype: FiscalYear
        """
        return util.deserialize_model(dikt, cls)

    @property
    def fiscal_year(self) -> int:
        """Gets the fiscal_year of this FiscalYear.


        :return: The fiscal_year of this FiscalYear.
        :rtype: int
        """
        return self._fiscal_year

    @fiscal_year.setter
    def fiscal_year(self, fiscal_year: int):
        """Sets the fiscal_year of this FiscalYear.


        :param fiscal_year: The fiscal_year of this FiscalYear.
        :type fiscal_year: int
        """

        self._fiscal_year = fiscal_year
