# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from swagger_server.models.base_model_ import Model
from swagger_server.models.customer import Customer  # noqa: F401,E501
from swagger_server import util


class GetCustomers(Model):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """

    def __init__(
        self, count: int = None, customers: List[Customer] = None
    ):  # noqa: E501
        """GetCustomers - a model defined in Swagger

        :param count: The count of this GetCustomers.  # noqa: E501
        :type count: int
        :param customers: The customers of this GetCustomers.  # noqa: E501
        :type customers: List[Customer]
        """
        self.swagger_types = {"count": int, "customers": List[Customer]}

        self.attribute_map = {"count": "count", "customers": "customers"}
        self._count = count
        self._customers = customers

    @classmethod
    def from_dict(cls, dikt) -> "GetCustomers":
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The GetCustomers of this GetCustomers.  # noqa: E501
        :rtype: GetCustomers
        """
        return util.deserialize_model(dikt, cls)

    @property
    def count(self) -> int:
        """Gets the count of this GetCustomers.


        :return: The count of this GetCustomers.
        :rtype: int
        """
        return self._count

    @count.setter
    def count(self, count: int):
        """Sets the count of this GetCustomers.


        :param count: The count of this GetCustomers.
        :type count: int
        """

        self._count = count

    @property
    def customers(self) -> List[Customer]:
        """Gets the customers of this GetCustomers.


        :return: The customers of this GetCustomers.
        :rtype: List[Customer]
        """
        return self._customers

    @customers.setter
    def customers(self, customers: List[Customer]):
        """Sets the customers of this GetCustomers.


        :param customers: The customers of this GetCustomers.
        :type customers: List[Customer]
        """

        self._customers = customers
