# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from swagger_server.models.base_model_ import Model
from swagger_server.models.customer import Customer  # noqa: F401,E501
from swagger_server import util


class GetCustomer(Model):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """

    def __init__(self, customer: Customer = None):  # noqa: E501
        """GetCustomer - a model defined in Swagger

        :param customer: The customer of this GetCustomer.  # noqa: E501
        :type customer: Customer
        """
        self.swagger_types = {"customer": Customer}

        self.attribute_map = {"customer": "customer"}
        self._customer = customer

    @classmethod
    def from_dict(cls, dikt) -> "GetCustomer":
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The GetCustomer of this GetCustomer.  # noqa: E501
        :rtype: GetCustomer
        """
        return util.deserialize_model(dikt, cls)

    @property
    def customer(self) -> Customer:
        """Gets the customer of this GetCustomer.


        :return: The customer of this GetCustomer.
        :rtype: Customer
        """
        return self._customer

    @customer.setter
    def customer(self, customer: Customer):
        """Sets the customer of this GetCustomer.


        :param customer: The customer of this GetCustomer.
        :type customer: Customer
        """

        self._customer = customer
