# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from swagger_server.models.base_model_ import Model
from swagger_server.models.user import User  # noqa: F401,E501
from swagger_server import util


class GetUser(Model):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """

    def __init__(self, user: User = None):  # noqa: E501
        """GetUser - a model defined in Swagger

        :param user: The user of this GetUser.  # noqa: E501
        :type user: User
        """
        self.swagger_types = {"user": User}

        self.attribute_map = {"user": "user"}
        self._user = user

    @classmethod
    def from_dict(cls, dikt) -> "GetUser":
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The GetUser of this GetUser.  # noqa: E501
        :rtype: GetUser
        """
        return util.deserialize_model(dikt, cls)

    @property
    def user(self) -> User:
        """Gets the user of this GetUser.


        :return: The user of this GetUser.
        :rtype: User
        """
        return self._user

    @user.setter
    def user(self, user: User):
        """Sets the user of this GetUser.


        :param user: The user of this GetUser.
        :type user: User
        """

        self._user = user
