# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from swagger_server.models.base_model_ import Model
from swagger_server.models.user import User  # noqa: F401,E501
from swagger_server import util


class LoginResponse(Model):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """

    def __init__(self, token: str = None, user: User = None):  # noqa: E501
        """LoginResponse - a model defined in Swagger

        :param token: The token of this LoginResponse.  # noqa: E501
        :type token: str
        :param user: The user of this LoginResponse.  # noqa: E501
        :type user: User
        """
        self.swagger_types = {'token': str, 'user': User}

        self.attribute_map = {'token': 'token', 'user': 'user'}
        self._token = token
        self._user = user

    @classmethod
    def from_dict(cls, dikt) -> 'LoginResponse':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The LoginResponse of this LoginResponse.  # noqa: E501
        :rtype: LoginResponse
        """
        return util.deserialize_model(dikt, cls)

    @property
    def token(self) -> str:
        """Gets the token of this LoginResponse.


        :return: The token of this LoginResponse.
        :rtype: str
        """
        return self._token

    @token.setter
    def token(self, token: str):
        """Sets the token of this LoginResponse.


        :param token: The token of this LoginResponse.
        :type token: str
        """

        self._token = token

    @property
    def user(self) -> User:
        """Gets the user of this LoginResponse.


        :return: The user of this LoginResponse.
        :rtype: User
        """
        return self._user

    @user.setter
    def user(self, user: User):
        """Sets the user of this LoginResponse.


        :param user: The user of this LoginResponse.
        :type user: User
        """

        self._user = user
