# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from swagger_server.models.base_model_ import Model
from swagger_server import util


class Login(Model):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """

    def __init__(self, login: str = None, password: str = None):  # noqa: E501
        """Login - a model defined in Swagger

        :param login: The login of this Login.  # noqa: E501
        :type login: str
        :param password: The password of this Login.  # noqa: E501
        :type password: str
        """
        self.swagger_types = {'login': str, 'password': str}

        self.attribute_map = {'login': 'login', 'password': 'password'}
        self._login = login
        self._password = password

    @classmethod
    def from_dict(cls, dikt) -> 'Login':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The Login of this Login.  # noqa: E501
        :rtype: Login
        """
        return util.deserialize_model(dikt, cls)

    @property
    def login(self) -> str:
        """Gets the login of this Login.


        :return: The login of this Login.
        :rtype: str
        """
        return self._login

    @login.setter
    def login(self, login: str):
        """Sets the login of this Login.


        :param login: The login of this Login.
        :type login: str
        """

        self._login = login

    @property
    def password(self) -> str:
        """Gets the password of this Login.


        :return: The password of this Login.
        :rtype: str
        """
        return self._password

    @password.setter
    def password(self, password: str):
        """Sets the password of this Login.


        :param password: The password of this Login.
        :type password: str
        """

        self._password = password
