# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from swagger_server.models.base_model_ import Model
from swagger_server import util


class MonthRevenue(Model):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """

    def __init__(
        self, month_name: str = None, month_revenue: float = None
    ):  # noqa: E501
        """MonthRevenue - a model defined in Swagger

        :param month_name: The month_name of this MonthRevenue.  # noqa: E501
        :type month_name: str
        :param month_revenue: The month_revenue of this MonthRevenue.  # noqa: E501
        :type month_revenue: float
        """
        self.swagger_types = {'month_name': str, 'month_revenue': float}

        self.attribute_map = {
            'month_name': 'month_name',
            'month_revenue': 'month_revenue',
        }
        self._month_name = month_name
        self._month_revenue = month_revenue

    @classmethod
    def from_dict(cls, dikt) -> 'MonthRevenue':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The MonthRevenue of this MonthRevenue.  # noqa: E501
        :rtype: MonthRevenue
        """
        return util.deserialize_model(dikt, cls)

    @property
    def month_name(self) -> str:
        """Gets the month_name of this MonthRevenue.


        :return: The month_name of this MonthRevenue.
        :rtype: str
        """
        return self._month_name

    @month_name.setter
    def month_name(self, month_name: str):
        """Sets the month_name of this MonthRevenue.


        :param month_name: The month_name of this MonthRevenue.
        :type month_name: str
        """

        self._month_name = month_name

    @property
    def month_revenue(self) -> float:
        """Gets the month_revenue of this MonthRevenue.


        :return: The month_revenue of this MonthRevenue.
        :rtype: float
        """
        return self._month_revenue

    @month_revenue.setter
    def month_revenue(self, month_revenue: float):
        """Sets the month_revenue of this MonthRevenue.


        :param month_revenue: The month_revenue of this MonthRevenue.
        :type month_revenue: float
        """

        self._month_revenue = month_revenue
