# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from swagger_server.models.base_model_ import Model
from swagger_server.models.customer_revenue import CustomerRevenue  # noqa: F401,E501
from swagger_server import util


class RevenueByCustomer(Model):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """

    def __init__(
        self, max_revenue_amount: float = None, revenue: List[CustomerRevenue] = None
    ):  # noqa: E501
        """RevenueByCustomer - a model defined in Swagger

        :param max_revenue_amount: The max_revenue_amount of this RevenueByCustomer.  # noqa: E501
        :type max_revenue_amount: float
        :param revenue: The revenue of this RevenueByCustomer.  # noqa: E501
        :type revenue: List[CustomerRevenue]
        """
        self.swagger_types = {
            "max_revenue_amount": float,
            "revenue": List[CustomerRevenue],
        }

        self.attribute_map = {
            "max_revenue_amount": "max_revenue_amount",
            "revenue": "revenue",
        }
        self._max_revenue_amount = max_revenue_amount
        self._revenue = revenue

    @classmethod
    def from_dict(cls, dikt) -> "RevenueByCustomer":
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The RevenueByCustomer of this RevenueByCustomer.  # noqa: E501
        :rtype: RevenueByCustomer
        """
        return util.deserialize_model(dikt, cls)

    @property
    def max_revenue_amount(self) -> float:
        """Gets the max_revenue_amount of this RevenueByCustomer.


        :return: The max_revenue_amount of this RevenueByCustomer.
        :rtype: float
        """
        return self._max_revenue_amount

    @max_revenue_amount.setter
    def max_revenue_amount(self, max_revenue_amount: float):
        """Sets the max_revenue_amount of this RevenueByCustomer.


        :param max_revenue_amount: The max_revenue_amount of this RevenueByCustomer.
        :type max_revenue_amount: float
        """

        self._max_revenue_amount = max_revenue_amount

    @property
    def revenue(self) -> List[CustomerRevenue]:
        """Gets the revenue of this RevenueByCustomer.


        :return: The revenue of this RevenueByCustomer.
        :rtype: List[CustomerRevenue]
        """
        return self._revenue

    @revenue.setter
    def revenue(self, revenue: List[CustomerRevenue]):
        """Sets the revenue of this RevenueByCustomer.


        :param revenue: The revenue of this RevenueByCustomer.
        :type revenue: List[CustomerRevenue]
        """

        self._revenue = revenue
