# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from swagger_server.models.base_model_ import Model
from swagger_server import util


class TotalRevenue(Model):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """

    def __init__(
        self, total_revenue: float = None, max_revenue_amount: float = None
    ):  # noqa: E501
        """TotalRevenue - a model defined in Swagger

        :param total_revenue: The total_revenue of this TotalRevenue.  # noqa: E501
        :type total_revenue: float
        :param max_revenue_amount: The max_revenue_amount of this TotalRevenue.  # noqa: E501
        :type max_revenue_amount: float
        """
        self.swagger_types = {
            'total_revenue': float,
            'max_revenue_amount': float,
        }

        self.attribute_map = {
            'total_revenue': 'total_revenue',
            'max_revenue_amount': 'max_revenue_amount',
        }
        self._total_revenue = total_revenue
        self._max_revenue_amount = max_revenue_amount

    @classmethod
    def from_dict(cls, dikt) -> 'TotalRevenue':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The TotalRevenue of this TotalRevenue.  # noqa: E501
        :rtype: TotalRevenue
        """
        return util.deserialize_model(dikt, cls)

    @property
    def total_revenue(self) -> float:
        """Gets the total_revenue of this TotalRevenue.


        :return: The total_revenue of this TotalRevenue.
        :rtype: float
        """
        return self._total_revenue

    @total_revenue.setter
    def total_revenue(self, total_revenue: float):
        """Sets the total_revenue of this TotalRevenue.


        :param total_revenue: The total_revenue of this TotalRevenue.
        :type total_revenue: float
        """

        self._total_revenue = total_revenue

    @property
    def max_revenue_amount(self) -> float:
        """Gets the max_revenue_amount of this TotalRevenue.


        :return: The max_revenue_amount of this TotalRevenue.
        :rtype: float
        """
        return self._max_revenue_amount

    @max_revenue_amount.setter
    def max_revenue_amount(self, max_revenue_amount: float):
        """Sets the max_revenue_amount of this TotalRevenue.


        :param max_revenue_amount: The max_revenue_amount of this TotalRevenue.
        :type max_revenue_amount: float
        """

        self._max_revenue_amount = max_revenue_amount
